services:
  - type: web
    name: NoteFlow-ClassificationModel
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://bharath2005goo:bharath2634@cluster0.hssjvxz.mongodb.net/
